### ISSUE TITLE
Signer does not understand new Buildkite `group` and `matrix` steps

### ISSUE THREAD

**Issue by gitlon** [buildkite/buildkite-signed-pipeline#40]
The pipeline-signer does not understand the new Buildkite `group` step. Commands in these steps are not signed, and therefore fail during the "checking signature" phase (with the `Signature mismatch.` error).

This is because the signer expects "steps" to be a child of the root of the pipeline yaml. Instead, any command in any part of the pipeline file should be signed.

Buildkite refs:
- https://buildkite.com/blog/announcing-the-new-group-step-type
- https://buildkite.com/docs/pipelines/group-step

I assume the code around this area should change:
- https://github.com/buildkite/buildkite-signed-pipeline/blob/master/cmd/buildkite-signed-pipeline/signer.go#L50

Also to note - I have not tested this but I assume the new Build Matrix `matrix` property will not work, for the same reasons.

- https://buildkite.com/docs/pipelines/build-matrix
- https://buildkite.com/blog/announcing-build-matrix

**Comment by jradtilbrook** [comment]
@gitlon we've scheduled to look into this and fix it in the next fortnight or so.  
So stay tuned

**Comment by jradtilbrook** [comment]
I've merged #41 now and will do a release shortly. `matrix` support is a little more complex and will be tackled separately

**Comment by baxang** [comment]
Looking forward to seeing `matrix` support soon.

**Comment by AngusWaller** [comment]
Hoping to see this resolved soon, my pipelines will become much more elegant with this functionality

**Comment by orolega** [comment]
What is the latest status of this?

**Comment by moskyb** [comment]
hey there! sorry about the radio silence from us.

we're working on this, in a roundabout kind of a way - we're currently working on integrating the pipeline upload signing process directly into the buildkite-agent, meaning that this supplementary binary would no longer be necessary. as part of this work, we're keen to look into supporting the signing of build-matrixed steps.

there's more complexity here than might be immediately apparent here though; matrix steps are "unrolled" serverside, meaning that those steps are actually created outside of an agent, meaning it would be difficult to sign those steps as an agent.

a couple of ideas we've had are:
- when a pipeline is being signed, "manually" unroll the matrix step as part of the pipeline upload, before it hits the server, then individually sign those unrolled steps. then, upload those steps. this would circumvent the serverside matrix feature, and undoubtedly cause some weird differences between the behaviour of signed matrix steps (which would be unrolled by the agent) and unsigned matrix steps (which would be unrolled by the buildkite backend).
- generate a signature against the matrix template (ie the step definition that has `{{ os }}` in it), and somehow attach that signature and the original matrix template to the step that gets generated. this would mean that agents would be able to verify that a step was generated through a given matrix template, but not that the correct matrix args were passed into it.

these are very early-days thoughts, and i'd be very interested to hear all of your opinions if you have them! feel free to keep commenting on this issue, or otherwise you can send me an email at ben.m@buildkite.com, or chat to me through either the community or the enterprise slack.

**Comment by moskyb** [comment]
hey friends! quick(ish) update from me on this.

the agent now (experimentally) supports in-band pipeline signing! it supports all of the stuff that this repo does and more - notably, on top of the capabilities of this project, it:
- Supports asymmetric signing
- Supports signing build matrices
- Signs pipeline env
- ... and much more

There's still more that we're working on, and things (like the API) are likely to change, so i wouldn't recommend using it for prod workloads just yet, but we're getting to a place where we're looking for feedback from a subset of customers. If you're interested in kicking the tyres on Signed Pipelines 2, please flick me a message on slack, or send me an email at ben.m@buildkite.com and i can flip on the backend feature flag that enables it.

**Comment by moskyb** [comment]
hey all! Pipeline Signing v2 was shipped as part of Agent [v3.60](https://github.com/buildkite/agent/releases/tag/v3.60.0) late last year, and signs both group and matrix steps with aplomb. we're probably going to archive this repo soon, but if you have any issues, please create an issue on the agent repo :)
